<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class DiscountRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $array = [
            'code' => 'required',
            'expire_time' => 'required',
            'amount' => 'required|numeric',
            'number_usable' => 'required|numeric',
        ];
        if (empty($this->amount_discount)) {
            $array['amount_percent'] = 'required';
        }
        return $array;
    }
    protected function getValidatorInstance()
    {
        if ($this->request->has('amount')) {
            $this->merge(['amount' => str_replace(',', '', $this->request->get('amount'))]);
        }
        if ($this->request->get('number_usable')) {
            $this->merge(['number_usable' => str_replace(',', '', $this->request->get('number_usable'))]);
        }
        if ($this->request->get('amount_discount')) {
            $this->merge(['amount_discount' => str_replace(',', '', $this->request->get('amount_discount'))]);
        }
        if ($this->request->get('amount_percent')) {
            $this->merge(['amount_percent' => str_replace(',', '', $this->request->get('amount_percent'))]);
        }
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub

    }
    public function attributes()
    {
        return [
            'code'=>'کد تخفیف',
            'expire_time'=>'تاریخ انقضاء',
            'amount'=>'حداقل خرید',
            'number_usable'=>'حداکثر دفعات استفاده',
            'amount_discount'=>'میزان کد تخفیف( بر حسب تومان )',
            'amount_percent'=>'میزان کد تخفیف( بر حسب درصد )',
        ];
    }
}
