<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected $table = 'category';
    protected $fillable = ['name', 'ename', 'url', 'img', 'search_url', 'parent_id', 'notShow'];

    public static function getParents()
    {
        $array = [0 => 'دسته اصلی'];
        $list = self::with('getChild.getChild')->where('parent_id', 0)->get();
        foreach ($list as $key => $value) {
            $array[$value->id] = $value->name;
            foreach ($value->getChild as $key1 => $value1) {
                $array[$value1->id] = ' - ' . $value1->name;
                foreach ($value1->getChild as $key2 => $value2) {
                    $array[$value2->id] = ' - - ' . $value2->name;
                }
            }
        }
        return $array;
    }
    public static function getParents2()
    {
        $array = ['' => 'انتخاب دسته بندی'];
        $list = self::with('getChild.getChild.getChild')->where('parent_id', 0)->get();
        foreach ($list as $key => $value) {
            $array[$value->id] = $value->name;
            foreach ($value->getChild as $key1 => $value1) {
                $array[$value1->id] = ' - ' . $value1->name;
                foreach ($value1->getChild as $key2 => $value2) {
                    $array[$value2->id] = ' - - ' . $value2->name;
                    foreach ($value2->getChild as $key3 => $value3) {
                        $array[$value3->id] = ' - - ' . $value3->name;
                    }
                }
            }
        }
        return $array;
    }

    public function getChild()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function getParent()
    {
        return $this->hasOne(Category::class, 'id', 'parent_id')
            ->withTrashed()->withDefault(['name' => '-']);
    }

    public static function getData($request)
    {
        $string = '?';
        $category = self::with('getParent');
        if (isTrashed($request)) {
            $category = $category->onlyTrashed();
            $string = create_paginate_url($string, 'trashed=true');
        }
        if (array_key_exists('string', $request) && !empty($request['string'])) {
            $category = $category->where('name', 'LIKE', '%' . $request['string'] . '%');
            $category = $category->orWhere('ename', 'LIKE', '%' . $request['string'] . '%');
            $string = create_paginate_url($string, 'string=' . $request['string']);
        }
        $category = $category->orderBy('id', 'Desc')->paginate(10);
        $category->withPath($string);
        return $category;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($category) {
            cache()->forget('catList');
            if ($category->isForceDeleting()) {
                remove_file($category->img, 'category/');
            }
            foreach ($category->getChild()->withTrashed()->get() as $value) {
                if ($category->isForceDeleting()) {
                    $value->fourceDelete();
                    remove_file($value->img, 'category/');
                } else
                    $value->delete();
            }
        });
        static::restoring(function ($category) {
            cache()->forget('catList');
            foreach ($category->getChild()->withTrashed()->get() as $value) {
                $value->restore();
            }
        });
    }
}
